name: transcendence

x-base: &base
  env_file:
    - .env
  networks:
    - transcendence
  volumes:
    - vault-ca:/ca
  restart: unless-stopped
  init: true

x-micro: &micro
  <<: *base
  # healthcheck:
  #   test: [ "CMD-SHELL", "python manage.py health_check || exit 1" ]
  #   interval: 5s
  #   timeout: 2s
  #   retries: 20
  #   start_period: 5s

x-db: &db
  <<: *base
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready" ]
    interval: 10s
    timeout: 5s
    retries: 5
  build:
    context: db
  shm_size: 128mb

services:
  nginx:
    <<: *base
    container_name: nginx
    build:
      context: frontend
    depends_on:
      auth:
        condition: service_started
    environment:
      - APP_RID=${NGINX_RID}
      - APP_SID=${NGINX_SID}
    volumes:
      - ./frontend/static:/usr/share/nginx/html
      - media-files:/media
      - nginx-ssl:/etc/ssl
      - static-files:/static
      - vault-ca:/ca
    ports:
      - "80:8080"
      - "443:8443"
  vault:
    <<: *base
    container_name: vault
    build:
      context: vault
      dockerfile: Dockerfile.server
    cap_add:
      - IPC_LOCK
    command: ["vault", "server", "-config=/vault/config/config.hcl"]
    volumes:
      - vault-ca:/vault/ca
      - vault-config:/vault/config
      - vault-data:/vault/file
      - vault-pki:/vault/pki
      - vault-ssl:/vault/ssl
  vault-init:
    <<: *base
    container_name: vault-init
    build:
      context: vault
      dockerfile: Dockerfile.init
    depends_on:
      vault:
        condition: service_started
    image: hashicorp/vault:1.17
    restart: no
    volumes:
      - vault-pki:/vault/pki
      - ./vault/ca:/export
      - vault-secrets:/vault/secrets
      - vault-ssl:/vault/ssl
  auth:
    <<: *micro
    container_name: auth
    build:
      context: backend
      args:
        APP_NAME: auth
        HOST: ${HOSTNAME}
    develop:
      watch:
        - action: sync+restart
          path: ./backend/auth/
          target: /auth/
    environment:
      - VAULT_ROLEID=${AUTH_RID}
      - VAULT_SECRETID=${AUTH_SID}
    env_file:
      - .env
    volumes:
      - auth-ssl:/etc/ssl
      - media-files:/media
      - static-files:/static
      - vault-ca:/ca
  auth-db:
    <<: *db
    container_name: auth-db
    environment:
      - DB_NAME=auth
    volumes:
      - auth-db:/var/lib/postgresql/data
  pong:
    <<: *micro
    container_name: pong
    build:
      context: backend
      args:
        APP_NAME: pong
        HOST: ${HOSTNAME}
    develop:
      watch:
        - action: sync+restart
          path: ./backend/pong/
          target: /pong/
    environment:
      - VAULT_ROLEID=${PONG_RID}
      - VAULT_SECRETID=${PONG_SID}
    env_file:
      - .env
    volumes:
      - media-files:/media
      - pong-ssl:/etc/ssl
      - static-files:/static
      - vault-ca:/ca
  pong-db:
    <<: *db
    container_name: pong-db
    environment:
      - DB_NAME=pong
    volumes:
      - pong-db:/var/lib/postgresql/data

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  auth-db:
  auth-ssl:
  media-files:
  nginx-ssl:
  pong-db:
  pong-ssl:
  static-files:
  vault-ca:
  vault-config:
  vault-data:
  vault-pki:
  vault-secrets:
  vault-ssl: